### ISSUE TITLE
Piwik cookies are no longer used

### ISSUE THREAD

**Issue by t3chguy** [vector-im/policies#17]
Riot no longer uses piwik.js (instead uses its own Piwik sending code) and now stores things as parts of its own application data in localStorage.

**Comment by deniseal** [comment]
Looking into creating app specific cookie policy (as opposed to current one that attempts to cover website+apps) as website still uses piwik cookies.

**Comment by deniseal** [comment]
I believe this has been resolved in the latest cookie policy update (https://element.io/cookie-policy).
