### ISSUE TITLE
Element use by kids?

### ISSUE THREAD

**Issue by BryanQuigley** [vector-im/policies#22]
I was wondering if there was any thoughts on making a child-parent account concept like Facebook's https://messengerkids.com/

In any case the smaller issue I'm reporting is that in [targeting educational instituions](https://element.io/blog/remote-schooling-health-safety-measures-shouldnt-put-our-kids-privacy-at-risk/) my quick read is that you need to update your terms and conditions, [namely the 16 year age limit](https://github.com/vector-im/policies/blob/master/docs/modular-im/terms_and_conditions.md#3-use-of-the-hosting-and-communication-services).

**Comment by deniseal** [comment]
@BryanQuigley sorry about the lag in getting back to you on this. For now we don't have a plan to change our age limit, as those are the terms for our SaaS offering. Individual schools and universities can set up their own servers and be in full control of their data and age limits.

I don't see a specific action here, so will go ahead and close this. If anything has changed in the meantime, please feel free to reopen.
