### ISSUE TITLE
Remove mention of __cfduid cookie in June 2021

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/policies#24]
https://blog.cloudflare.com/deprecating-cfduid-cookie/

**Comment by deniseal** [comment]
This was resolved in the latest update to the cookie policy: https://element.io/cookie-policy

**Comment by aaronraimist** [comment]
@deniseal is the version in this repository going to be updated? https://github.com/vector-im/policies/blob/master/docs/riot-im/cookie_policy.md

Would be nice to keep it updated so people can use Git to see how it has changed over time

**Comment by aaronraimist** [comment]
Ah I guess there is https://github.com/vector-im/policies/issues/25 for that
